Repository MindboxDevSchool/MindhubDevTeam, pull requests merged in 2020-11, with the labels that each got.

#86 Added DB&EF Repositories for: Comment, Event, Tracker. Some refactori…
  ItHappened.App/Startup.cs
  ItHappened/Application/EventService.cs
  ItHappened/Application/TrackerService.cs
  ItHappened/Application/UserService.cs
  ItHappened/Domain/Tracker.cs
  ItHappened/Infrastructure/CommentRepository.cs
  ItHappened/Infrastructure/CommonDbContext.cs
  ItHappened/Infrastructure/EventRepository.cs
  ItHappened/Infrastructure/TrackerRepository.cs
  ItHappened/Infrastructure/UserRepository.cs
Labels: Database

#84 Event and Customizations controllers
  ItHappened.App/Controller/CustomizationsController.cs
  ItHappened.App/Controller/EventController.cs
  ItHappened.App/Controller/TrackerController.cs
  ItHappened.App/Model/Customizations/CommentCreateRequest.cs
  ItHappened.App/Model/Customizations/CommentGetResponse.cs
  ItHappened.App/Model/Event/EventCreateRequest.cs
  ItHappened.App/Model/Event/EventGetResponse.cs
  ItHappened.App/Model/Tracker/TrackerGetResponse.cs
  ItHappened.App/PostmanCollections/MindHubItHappened.postman_collection.json
  ItHappened.App/PostmanCollections/TrackerController.postman_collection.json
  ItHappened.App/PostmanCollections/UserController.postman_collection.json
  ItHappened/Application/CustomizationService.cs
  ItHappened/Application/ICustomizationService.cs
Labels: ASP Net

#82 Panfilkin/67 create user frontend
  ItHappened.App/Controller/CustomizationsController.cs
  ItHappened.App/Controller/EventController.cs
  ItHappened.App/Controller/TrackerController.cs
  ItHappened.App/Controller/UserController.cs
  ItHappened/Application/UserService.cs
  ItHappened/Domain/User.cs
  ithappened.nodejs/debug.log
  ithappened.nodejs/package-lock.json
  ithappened.nodejs/package.json
  ithappened.nodejs/src/Api.js
  ithappened.nodejs/src/App.js
  ithappened.nodejs/src/User/UserApp.js
  ithappened.nodejs/src/User/UserEdit.js
  ithappened.nodejs/src/User/UserSignIn.js
  ithappened.nodejs/src/User/UserSignOut.js
  ithappened.nodejs/src/User/UserSignUp.js
Labels: Frontend

#64 StatsFacts, StatsService, StatsController
  ItHappened.App/Authentication/JwtClaimTypes.cs
  ItHappened.App/Controller/StatisticsController.cs
  ItHappened.App/Controller/StatsController.cs
  ItHappened.App/PostmanCollections/MindHubItHappened.postman_collection.json
  ItHappened.Tests/DateTimeExtensionsTests.cs
  ItHappened.Tests/StatsFactsTests.cs
  ItHappened/Application/Forms/TrackerForm.cs
  ItHappened/Application/StatsService.cs
  ItHappened/Domain/Stats/DateTimeExtensions.cs
  ItHappened/Domain/Stats/Facts/Overall/BiggestDayOverallStatsFact.cs
  ItHappened/Domain/Stats/Facts/Overall/BiggestWeekOverallStatsFact.cs
  ItHappened/Domain/Stats/Facts/Overall/ManyEventsOverallStatsFact.cs
  ItHappened/Domain/Stats/Facts/Trackers/BestTrackerEventStatsFact.cs
  ItHappened/Domain/Stats/Facts/Trackers/LongestBreakStatsFact.cs
  ItHappened/Domain/Stats/Facts/Trackers/TheMostEventStatsFact.cs
  ItHappened/Domain/Stats/Facts/Trackers/WorseTrackerEventStatsFact.cs
  ItHappened/Domain/Stats/IStatsFact.cs
  ItHappened/Domain/Stats/StatsFactType.cs
Labels: Feature

#92 [Full] Realisation of Tracker Frontend
  ItHappened.App/all.log
  ithappened.nodejs/src/Api.js
  ithappened.nodejs/src/App.js
  ithappened.nodejs/src/Components/Common/LinkButton.js
  ithappened.nodejs/src/Components/Tracker/TrackerCard.js
  ithappened.nodejs/src/Components/Tracker/TrackerCreateForm.js
  ithappened.nodejs/src/Components/Tracker/TrackerEditForm.js
  ithappened.nodejs/src/Components/Tracker/TrackerPreview.js
  ithappened.nodejs/src/Tracker/TrackerCreate.js
  ithappened.nodejs/src/Tracker/TrackerDetail.js
  ithappened.nodejs/src/Tracker/TrackerEdit.js
  ithappened.nodejs/src/Tracker/Trackers.js
  ithappened.nodejs/src/User/UserApp.js
  ithappened.nodejs/src/User/UserEdit.js
Labels: Frontend

#94 Realization of Event Frontend
  .gitignore
  ItHappened.App/Controller/EventController.cs
  ItHappened.App/Model/Customizations/CreateRequests/CommentCreateRequest.cs
  ItHappened.App/Model/Customizations/CreateRequests/CustomizationsCreateRequests.cs
  ItHappened.App/Model/Customizations/CreateRequests/PhotoCreateRequest.cs
  ItHappened.App/Model/Customizations/GetResponses/CustomizationsGetResponses.cs
  ItHappened.App/Model/Customizations/GetResponses/PhotoGetResponse.cs
  ItHappened.App/PostmanCollections/MindHubItHappened.postman_collection.json
  ItHappened.App/all.log
  ItHappened/Application/CustomizationService.cs
  ItHappened/Application/Forms/PhotoForm.cs
  ItHappened/Application/ICustomizationService.cs
  ItHappened/Domain/Customizations/Photo.cs
  ithappened.nodejs/package-lock.json
  ithappened.nodejs/package.json
  ithappened.nodejs/src/Api.js
  ithappened.nodejs/src/App.js
  ithappened.nodejs/src/Components/Event/Customization/CommentForm.js
  ithappened.nodejs/src/Components/Event/Customization/CommentReadonly.js
  ithappened.nodejs/src/Components/Event/Customization/GeotagForm.js
  ithappened.nodejs/src/Components/Event/Customization/GeotagReadonly.js
  ithappened.nodejs/src/Components/Event/Customization/PhotoBase64.js
  ithappened.nodejs/src/Components/Event/Customization/PhotoForm.js
  ithappened.nodejs/src/Components/Event/Customization/RatingForm.js
  ithappened.nodejs/src/Components/Event/Customization/RatingReadonly.js
  ithappened.nodejs/src/Components/Event/Customization/ScaleForm.js
  ithappened.nodejs/src/Components/Event/Customization/ScaleReadonly.js
  ithappened.nodejs/src/Components/Event/EventCard.js
  ithappened.nodejs/src/Components/Event/EventCreateForm.js
  ithappened.nodejs/src/Components/Event/EventEditForm.js
  ithappened.nodejs/src/Components/Event/EventPreview.js
  ithappened.nodejs/src/Components/Tracker/TrackerCard.js
  ithappened.nodejs/src/Components/Tracker/TrackerCreateForm.js
  ithappened.nodejs/src/Event/EventCreate.js
  ithappened.nodejs/src/Event/EventDetail.js
  ithappened.nodejs/src/Event/EventEdit.js
  ithappened.nodejs/src/Tracker/TrackerDetail.js
  ithappened.nodejs/src/Tracker/Trackers.js
Labels: Frontend

#98 Add stats fronted
  ithappened.nodejs/src/Api.js
  ithappened.nodejs/src/App.js
  ithappened.nodejs/src/Components/Stats/StatsFactCard.js
  ithappened.nodejs/src/Stats/StatsView.js
Labels: Frontend
